# Generated by Django 3.2 on 2021-08-15 23:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('languages', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Translator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='translator_creators', to=settings.AUTH_USER_MODEL)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='translator_languages', to='languages.language')),
                ('modifier', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='translat0r_modifiers', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='translator_users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
