# Generated by Django 3.2.6 on 2021-09-01 19:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0007_alter_term_term'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('languages', '0004_auto_20210826_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='code',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='language',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='language',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='language_creators', to=settings.AUTH_USER_MODEL, verbose_name='Creator'),
        ),
        migrations.AlterField(
            model_name='language',
            name='language',
            field=models.CharField(max_length=100, verbose_name='Language'),
        ),
        migrations.AlterField(
            model_name='language',
            name='modified',
            field=models.DateTimeField(auto_now=True, verbose_name='Modified'),
        ),
        migrations.AlterField(
            model_name='language',
            name='modifier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='language_modifiers', to=settings.AUTH_USER_MODEL, verbose_name='Modifier'),
        ),
        migrations.AlterField(
            model_name='translation',
            name='content',
            field=models.TextField(blank=True, verbose_name='Translation Content'),
        ),
        migrations.AlterField(
            model_name='translation',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creaed'),
        ),
        migrations.AlterField(
            model_name='translation',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='translation_creators', to=settings.AUTH_USER_MODEL, verbose_name='Creator'),
        ),
        migrations.AlterField(
            model_name='translation',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='translation_languages', to='languages.language', verbose_name='Language'),
        ),
        migrations.AlterField(
            model_name='translation',
            name='modified',
            field=models.DateTimeField(auto_now=True, verbose_name='Modified'),
        ),
        migrations.AlterField(
            model_name='translation',
            name='modifier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='translation_modifiers', to=settings.AUTH_USER_MODEL, verbose_name='Modifier'),
        ),
        migrations.AlterField(
            model_name='translation',
            name='text',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translation_texts', to='trainings.text', verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='translator',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='translator',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='translator_creators', to=settings.AUTH_USER_MODEL, verbose_name='Creator'),
        ),
        migrations.AlterField(
            model_name='translator',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='translator_languages', to='languages.language', verbose_name='Language'),
        ),
        migrations.AlterField(
            model_name='translator',
            name='modified',
            field=models.DateTimeField(auto_now=True, verbose_name='Modified'),
        ),
        migrations.AlterField(
            model_name='translator',
            name='modifier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='translat0r_modifiers', to=settings.AUTH_USER_MODEL, verbose_name='Modifier'),
        ),
        migrations.AlterField(
            model_name='translator',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='translator_users', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
