# Generated by Django 3.2 on 2021-08-13 21:51

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('languages', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('first_name', models.CharField(max_length=120)),
                ('last_name', models.CharField(max_length=120)),
                ('chinese_name', models.CharField(max_length=6)),
                ('gender', models.CharField(choices=[('B', 'Brother'), ('S', 'Sister')], max_length=10)),
                ('district', models.CharField(max_length=8)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=10, region=None, validators=[django.core.validators.RegexValidator(message='Please enter your 10-digit phone number (including area code) without dashes or anything else.', regex='^[(]?[2-9]\\d{2}[) -.]{0,2}\\d{3}[ -.]?\\d{4}$')])),
                ('email', models.CharField(max_length=255, unique=True, validators=[django.core.validators.EmailValidator()])),
                ('is_staff', models.BooleanField()),
                ('is_superuser', models.BooleanField()),
                ('last_login', models.DateTimeField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(related_name='user_groups', to='auth.Group')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='user_languages', to='languages.language', verbose_name='Primary Language')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='usertype_creators', to=settings.AUTH_USER_MODEL)),
                ('modifier', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='usertype_modifiers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Locality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locality', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='locality_creators', to=settings.AUTH_USER_MODEL)),
                ('modifier', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='locality_modifiers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='locality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='user_localities', to='users.locality'),
        ),
        migrations.AddField(
            model_name='user',
            name='modifier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='user_modifiers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(related_name='user_userpermissions', to='auth.Permission'),
        ),
        migrations.AddField(
            model_name='user',
            name='usertypes',
            field=models.ManyToManyField(related_name='user_usertypes', to='users.UserType'),
        ),
    ]
