# Generated by Django 3.2 on 2021-08-14 10:18

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0002_initial'),
        ('users', '0005_auto_20210814_1016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='district',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('B', 'Brother'), ('S', 'Sister')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='user_languages', to='languages.language', verbose_name='Primary Language'),
        ),
        migrations.AlterField(
            model_name='user',
            name='locality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='user_localities', to='users.locality'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=10, null=True, region=None, validators=[django.core.validators.RegexValidator(message='Please enter your 10-digit phone number (including area code) without dashes or anything else.', regex='^[(]?[2-9]\\d{2}[) -.]{0,2}\\d{3}[ -.]?\\d{4}$')]),
        ),
    ]
