# Generated by Django 3.2 on 2021-08-14 11:29

import django.core.validators
from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20210814_1018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=10, null=True, region=None, validators=[django.core.validators.RegexValidator(message='Please enter your 10-digit phone number including your area code.', regex='^[(]?[2-9]\\d{2}[) -.]{0,2}\\d{3}[ -.]?\\d{4}$')]),
        ),
    ]
