# Generated by Django 3.2 on 2021-08-21 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_user_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='locality',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='usertype',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
