from django.urls import path

from . import views

app_name = 'trainings'
urlpatterns = [
    path('term/index/', views.term_index, name = 'term_index'),
    path('term/view/<int:term_id>/', views.term_view, name = 'term_view'),
    path('term/add/', views.term_add, name = 'term_add'),
    path('term/edit/<int:term_id>/', views.term_edit, name = 'term_edit'),
    path('term/delete/<int:term_id>/', views.term_delete, name = 'term_delete'),
    path('exercisetype/index/', views.exercisetype_index, name = 'exercisetype_index'),
    path('exercisetype/view/<int:exercisetype_id>/', views.exercisetype_view, name = 'exercisetype_view'),
    path('exercisetype/add/', views.exercisetype_add, name = 'exercisetype_add'),
    path('exercisetype/edit/<int:exercisetype_id>/', views.exercisetype_edit, name = 'exercisetype_edit'),
    path('exercisetype/delete/<int:exercisetype_id>/', views.exercisetype_delete, name = 'exercisetype_delete'),
    path('recordinglocation/index/', views.recordinglocation_index, name = 'recordinglocation_index'),
    path('recordinglocation/view/<int:recordinglocation_id>/', views.recordinglocation_view, name = 'recordinglocation_view'),
    path('recordinglocation/add/', views.recordinglocation_add, name = 'recordinglocation_add'),
    path('recordinglocation/edit/<int:recordinglocation_id>/', views.recordinglocation_edit, name = 'recordinglocation_edit'),
    path('recordinglocation/delete/<int:recordinglocation_id>/', views.recordinglocation_delete, name = 'recordinglocation_delete'),
    path('registration/index/', views.registration_index, name = 'registration_index'),
    path('registration/view/<int:registration_id>/', views.registration_view, name = 'registration_view'),
    path('registration/add/', views.registration_add, name = 'registration_add'),
    path('registration/edit/<int:registration_id>/', views.registration_edit, name = 'registration_edit'),
    path('registration/delete/<int:registration_id>/', views.registration_delete, name = 'registration_delete'),
    path('trainingmeeting/index/', views.trainingmeeting_index, name = 'trainingmeeting_index'),
    path('trainingmeeting/view/<int:trainingmeeting_id>/', views.trainingmeeting_view, name = 'trainingmeeting_view'),
    path('trainingmeeting/add/', views.trainingmeeting_add, name = 'trainingmeeting_add'),
    path('trainingmeeting/edit/<int:trainingmeeting_id>/', views.trainingmeeting_edit, name = 'trainingmeeting_edit'),
    path('trainingmeeting/delete/<int:trainingmeeting_id>/', views.trainingmeeting_delete, name = 'trainingmeeting_delete'),
    path('userexercise/index/', views.userexercise_index, name = 'userexercise_index'),
    path('userexercise/view/<int:userexercise_id>/', views.userexercise_view, name = 'userexercise_view'),
    path('userexercise/add/', views.userexercise_add, name = 'userexercise_add'),
    path('userexercise/edit/<int:userexercise_id>/', views.userexercise_edit, name = 'userexercise_edit'),
    path('userexercise/delete/<int:userexercise_id>/', views.userexercise_delete, name = 'userexercise_delete'),
    path('text/index/', views.text_index, name = 'text_index'),
    path('text/view/<int:text_id>/', views.text_view, name = 'text_view'),
    path('text/add/', views.text_add, name = 'text_add'),
    path('text/edit/<int:text_id>/', views.text_edit, name = 'text_edit'),
    path('text/delete/<int:text_id>/', views.text_delete, name = 'text_delete'),
]