# Generated by Django 3.2 on 2021-08-13 21:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trainings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('languages', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userexercise',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='userexercise_creators', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userexercise',
            name='exercisetypes',
            field=models.ManyToManyField(related_name='userexercise_exercisetypes', to='trainings.ExerciseType'),
        ),
        migrations.AddField(
            model_name='userexercise',
            name='modifier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='userexercise_modifiers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userexercise',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='userexercise_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trainingmeeting',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='trainingmeeting_creators', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trainingmeeting',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='trainingmeeting_languages', to='languages.language'),
        ),
        migrations.AddField(
            model_name='trainingmeeting',
            name='modifier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='trainingmeeting_modifiers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='text',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='text_creators', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='text',
            name='modifier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='text_modifiers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='term',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='term_creators', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='term',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='term_languages', to='languages.language'),
        ),
        migrations.AddField(
            model_name='term',
            name='modifier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='term_modifiers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='registration',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='registration_creators', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='registration',
            name='exercisetypes',
            field=models.ManyToManyField(related_name='registration_exercisetypes', to='trainings.ExerciseType'),
        ),
        migrations.AddField(
            model_name='registration',
            name='modifier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='registration_modifiers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='registration',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='registration_terms', to='trainings.term'),
        ),
        migrations.AddField(
            model_name='registration',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='registration_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recordinglocation',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='recordinglocation_creators', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recordinglocation',
            name='modifier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='recordinglocation_modifiers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='exercisetype',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='exercisetype_creators', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='exercisetype',
            name='modifier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='exercisetype_modifiers', to=settings.AUTH_USER_MODEL),
        ),
    ]
