# Generated by Django 3.2 on 2021-08-17 18:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trainings', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingmeeting',
            name='recording_released_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='recordingreleased_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trainingmeeting',
            name='recording_released_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trainingmeeting',
            name='recording_url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
