# Generated by Django 3.2 on 2021-08-21 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0003_auto_20210817_1852'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercisetype',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
