# Generated by Django 3.2 on 2021-08-26 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0005_auto_20210826_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='exercisetypes',
            field=models.ManyToManyField(blank=True, related_name='registration_exercisetypes', to='trainings.ExerciseType'),
        ),
    ]
