# Generated by Django 3.2 on 2021-08-27 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0006_alter_registration_exercisetypes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='term',
            name='term',
            field=models.CharField(choices=[('Fall', 'Fall'), ('Spring', 'Spring')], max_length=10),
        ),
    ]
