# Generated by Django 3.2.6 on 2021-09-13 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0008_auto_20210901_1905'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingmeeting',
            name='recordinglocation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='trainingmeeting_recordinglocations', to='trainings.recordinglocation', verbose_name='Recording Location'),
        ),
    ]
