"""
Django settings for newwinetraining project.

Generated by 'django-admin startproject' using Django 3.2.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from inspect import EndOfBlock
from pathlib import Path

import environ

# Initialise environment variables
env = environ.Env()
environ.Env.read_env()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env('DEBUG')
#DEBUG = False

ALLOWED_HOSTS = env('ALLOWED_HOSTS')
#ALLOWED_HOSTS = []

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',

    #third party apps
    'phonenumber_field',
    'iommi',
#    'stronghold',
    
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    # ... include the providers you want to enable:
    #'allauth.socialaccount.providers.agave',
    #'allauth.socialaccount.providers.amazon',
    #'allauth.socialaccount.providers.amazon_cognito',
    #'allauth.socialaccount.providers.angellist',
    #'allauth.socialaccount.providers.apple', #TODO
    #'allauth.socialaccount.providers.asana',
    #'allauth.socialaccount.providers.auth0',
    #'allauth.socialaccount.providers.authentiq',
    #'allauth.socialaccount.providers.azure', #TODO
    #'allauth.socialaccount.providers.baidu',
    #'allauth.socialaccount.providers.basecamp',
    #'allauth.socialaccount.providers.battlenet',
    #'allauth.socialaccount.providers.bitbucket',
    #'allauth.socialaccount.providers.bitbucket_oauth2',
    #'allauth.socialaccount.providers.bitly',
    #'allauth.socialaccount.providers.box',
    #'allauth.socialaccount.providers.cern',
    #'allauth.socialaccount.providers.cilogon',
    #'allauth.socialaccount.providers.coinbase',
    #'allauth.socialaccount.providers.dataporten',
    #'allauth.socialaccount.providers.daum',
    #'allauth.socialaccount.providers.digitalocean',
    #'allauth.socialaccount.providers.discord', #TODO
    #'allauth.socialaccount.providers.disqus',
    #'allauth.socialaccount.providers.douban',
    #'allauth.socialaccount.providers.doximity',
    #'allauth.socialaccount.providers.draugiem',
    #'allauth.socialaccount.providers.dropbox',
    #'allauth.socialaccount.providers.dwolla',
    #'allauth.socialaccount.providers.edmodo',
    #'allauth.socialaccount.providers.edx',
    #'allauth.socialaccount.providers.eventbrite',
    #'allauth.socialaccount.providers.eveonline',
    #'allauth.socialaccount.providers.evernote',
    #'allauth.socialaccount.providers.exist',
    #'allauth.socialaccount.providers.facebook', #TODO
    #'allauth.socialaccount.providers.feedly',
    #'allauth.socialaccount.providers.figma',
    #'allauth.socialaccount.providers.fivehundredpx',
    #'allauth.socialaccount.providers.flickr',
    #'allauth.socialaccount.providers.foursquare',
    #'allauth.socialaccount.providers.frontier',
    #'allauth.socialaccount.providers.fxa',
    #'allauth.socialaccount.providers.github',
    #'allauth.socialaccount.providers.gitlab',
    #'allauth.socialaccount.providers.globus',
    'allauth.socialaccount.providers.google',
    #'allauth.socialaccount.providers.hubic',
    #'allauth.socialaccount.providers.instagram',
    #'allauth.socialaccount.providers.jupyterhub',
    #'allauth.socialaccount.providers.kakao',
    #'allauth.socialaccount.providers.keycloak',
    #'allauth.socialaccount.providers.line', #TODO
    #'allauth.socialaccount.providers.linkedin',
    #'allauth.socialaccount.providers.linkedin_oauth2',
    #'allauth.socialaccount.providers.mailchimp',
    #'allauth.socialaccount.providers.mailru',
    #'allauth.socialaccount.providers.meetup',
    #'allauth.socialaccount.providers.microsoft', #TODO
    #'allauth.socialaccount.providers.naver',
    #'allauth.socialaccount.providers.nextcloud',
    #'allauth.socialaccount.providers.odnoklassniki',
    #'allauth.socialaccount.providers.openid',
    #'allauth.socialaccount.providers.openstreetmap',
    #'allauth.socialaccount.providers.orcid',
    #'allauth.socialaccount.providers.patreon',
    #'allauth.socialaccount.providers.paypal',
    #'allauth.socialaccount.providers.persona',
    #'allauth.socialaccount.providers.pinterest',
    #'allauth.socialaccount.providers.quickbooks',
    #'allauth.socialaccount.providers.reddit',
    #'allauth.socialaccount.providers.robinhood',
    #'allauth.socialaccount.providers.salesforce',
    #'allauth.socialaccount.providers.sharefile',
    #'allauth.socialaccount.providers.shopify',
    #'allauth.socialaccount.providers.slack',
    #'allauth.socialaccount.providers.soundcloud',
    #'allauth.socialaccount.providers.spotify',
    #'allauth.socialaccount.providers.stackexchange',
    #'allauth.socialaccount.providers.steam',
    #'allauth.socialaccount.providers.stocktwits',
    #'allauth.socialaccount.providers.strava',
    #'allauth.socialaccount.providers.stripe',
    #'allauth.socialaccount.providers.telegram',
    #'allauth.socialaccount.providers.trainingpeaks',
    #'allauth.socialaccount.providers.trello',
    #'allauth.socialaccount.providers.tumblr',
    #'allauth.socialaccount.providers.twentythreeandme',
    #'allauth.socialaccount.providers.twitch',
    #'allauth.socialaccount.providers.twitter',
    #'allauth.socialaccount.providers.untappd',
    #'allauth.socialaccount.providers.vimeo',
    #'allauth.socialaccount.providers.vimeo_oauth2',
    #'allauth.socialaccount.providers.vk',
    #'allauth.socialaccount.providers.weibo',
    #'allauth.socialaccount.providers.weixin', #TODO
    #'allauth.socialaccount.providers.windowslive', #TODO
    #'allauth.socialaccount.providers.xing',
    #'allauth.socialaccount.providers.yahoo', #TODO
    #'allauth.socialaccount.providers.yandex',
    #'allauth.socialaccount.providers.ynab',
    #'allauth.socialaccount.providers.zoho',
    #'allauth.socialaccount.providers.zoom',
    #'allauth.socialaccount.providers.okta',
    #'allauth.socialaccount.providers.feishu',

    #own apps
    'languages',
    'trainings',
    'users',
    'pages',
]
"""
try:
    import django_fastdev
except ImportError:
    pass
else:
    INSTALLED_APPS += ['django_fastdev']
"""
MIDDLEWARE = [
    'iommi.live_edit.Middleware', #Must be first in the list

    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'BrokenLinkEmailsMiddleware',
    
    'stronghold.middleware.LoginRequiredMiddleware',

    'iommi.sql_trace.Middleware',
    'iommi.profiling.Middleware',
    'iommi.middleware', #must be last in the list
]

ROOT_URLCONF = 'newwinetraining.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR, 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'newwinetraining.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'HOST': env('DATABASE_HOST'),
        'NAME': env('DATABASE_NAME'),
        'USER': env('DATABASE_USER'),
        'PASSWORD': env('DATABASE_PASS'),
        'PORT': env('DATABASE_PORT'),
    }
}

EMAIL_HOST = env('EMAIL_HOST')
EMAIL_HOST_PASSWORD = env('EMAIL_HOST_PASSWORD')
EMAIL_HOST_USER = env('EMAIL_HOST_USER')
EMAIL_PORT = env('EMAIL_PORT')
EMAIL_SUBJECT_PREFIX = '[New Wine Training]'
EMAIL_USE_LOCALTIME = True
EMAIL_USE_SSL = True
DEFAULT_FROM_EMAIL = env('DEFAULT_FROM_EMAIL')
SERVER_EMAIL = env('SERVER_EMAIL')

# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {
            'min_length': 6,
        }
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

AUTHENTICATION_BACKENDS = [
    # Needed to login by username in Django admin, regardless of `allauth`
    'django.contrib.auth.backends.ModelBackend',

    # `allauth` specific authentication methods, such as login by e-mail
    'allauth.account.auth_backends.AuthenticationBackend',
]

# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'America/Los_Angeles'

USE_I18N = True

USE_L10N = True

USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'

STATICFILES_DIRS = [
    BASE_DIR / "static",
]

MEDIA_URL = None

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

#Custom User database for auth
AUTH_USER_MODEL = 'users.User'

LOGIN_URL = '/accounts/login'

LOGIN_REDIRECT_URL = '/'

ADMINS = env('ADMINS')

LANGUAGE_COOKIE_AGE = None

MANAGERS = env('ADMINS')

#Setting up default phone number region for validation
PHONENUMBER_DEFAULT_REGION = 'US'

#Stronghold settings

STRONGHOLD_DEFAULTS = True

STRONGHOLD_PUBLIC_URLS = (
    r'^/accounts/login.+$',
    r'^/accounts/apple/login.*$',
    r'^/accounts/azure/login.*$',
    r'^/accounts/baidu/login.*$',
    r'^/accounts/discord/login.*$',
    r'^/accounts/google/login.*$',
    r'^/accounts/line/login.*$',
    r'^/accounts/microsoft/login.*$',
    r'^/accounts/weixin/login.*$',
    r'^/accounts/windowslive/login.*$',
    r'^/accounts/yahoo/login.*$',
    r'^/accounts/confirm-email.*$',
)

STRONGHOLD_PUBLIC_NAMED_URLS = ('account_logout', 'account_set_password', 'account_signup', 'account_confirm_email','account_reset_password', 'users:user_register')

STRONGHOLD_USER_TEST_FUNC = lambda user: user.is_staff

#AllAuth Settings
SITE_ID = 1

ACCOUNT_AUTHENTICATION_METHOD = 'email'

ACCOUNT_USER_MODEL_USERNAME_FIELD = None

ACCOUNT_USERNAME_REQUIRED = False

ACCOUNT_EMAIL_CONFIRMATION_ANONYMOUS_REDIRECT_URL = '/trainings/registration/add/'

ACCOUNT_EMAIL_CONFIRMATION_AUTHENTICATED_REDIRECT_URL = '/trainings/registration/add/'

ACCOUNT_EMAIL_REQUIRED = True

ACCOUNT_EMAIL_VERIFICATION = 'mandatory' #mandatory, optional, none

ACCOUNT_EMAIL_SUBJECT_PREFIX = '[New Wine Training]'

ACCOUNT_DEFAULT_HTTP_PROTOCOL = 'https'

ACCOUNT_LOGIN_ON_EMAIL_CONFIRMATION = True

ACCOUNT_LOGOUT_ON_PASSWORD_CHANGE = True

ACCOUNT_SIGNUP_EMAIL_ENTER_TWICE = True

#Iommi hook to use project style

#Don't put any imports after this line
from iommi import Style, Asset
from iommi.style_bootstrap import bootstrap

#IOMMI_DEFAULT_STYLE = 'bulma' #base, test, bootstrap, bulma, foundation, semantic_ui, water, django_admin


IOMMI_DEFAULT_STYLE = Style(
    bootstrap,
    base_template='templates/iommi/iommi_base.html',
    root__assets=dict(
        newwinetraining_sb_admin_2_css = Asset.css(attrs__href = STATIC_URL + 'css/sb-admin-2.min.css'),
        newwinetraining_custom_css = Asset.css(attrs__href = STATIC_URL + 'css/custom.css'),
        newwinetraining_sb_admin_2_js = Asset.js(attrs__src = STATIC_URL + 'js/sb-admin-2.min.js'),
    ),
)


#Disabling pycache for development environments
#if env('DEBUG') == True:
#    os.environ['PYTHONDONTWRITEBYTECODE'] = 1

#os.environ['PYTHONDONTWRITEBYTECODE'] = '1'

#dfdsfjlkdsjf()

#from thisdoesnotexistforsure import kaboom